[settings]
default_action = "all"

[actions.all]
description = "Run all test jobs. They will fail."
is_entrypoint = true
dependencies = ["gcc", "npm", "go", "make"]

[actions.gcc]
description = "Simulate a failing gcc build."
shell = "cat testdata/gcc.log && false"
message = "This is a custom message from the failing gcc job."

[actions.npm]
description = "Simulate a failing npm build."
shell = "cat testdata/npm.log && false"
message = "This is a message from the failing npm job."

[actions.go]
description = "Simulate a failing go build."
shell = "cat testdata/go.log && false"

[actions.make]
description = "Simulate a failing make run."
shell = "cat testdata/make.log && false"
